#server:
#  port: 8081
#  servlet:
#    context-path: /employee
#
#spring:
#  datasource:
#    url: jdbc:mysql://mysql-employee:3308/employee_service
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#
#jwt:
#  secret: 5a17ebf57445277d088804588e896e6ae347ec9815f9f9f0b95065101e022eb8
#  expiration-days: 180


server:
  port: 8081

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/employee_service
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# B?T BU?C cho Hibernate 7 + Boot 4
jakarta:
  persistence:
    jdbc:
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/employee_service
